language: node_js
node_js:
  - '6'
  - '4'

branches:
  only:
    - master
    - /^greenkeeper-.*$/

cache:
  directories:
    - node_modules

script:
  - npm run cover

after_script:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
