language: node_js
node_js:
  - "7"
  - "6"
  - "4"
  - "0.12"
  - "iojs"

branches:
  only:
    - master
    - /^greenkeeper-.*$/

cache:
  directories:
    - node_modules

script:
  - npm run cover

after_script:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
